/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleOperatorRouteImport } from './routes/$locale.operator'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleSearchRouteImport } from './routes/$locale.search'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as LocaleExperiencesSlugRouteImport } from './routes/$locale.experiences.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOperatorRoute = LocaleOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRoute,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleExperiencesSlugRoute = LocaleExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/operator': typeof OperatorRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/$locale/operator': typeof LocaleOperatorRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/experiences/$slug': typeof LocaleExperiencesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/operator': typeof OperatorRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/$locale/operator': typeof LocaleOperatorRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/experiences/$slug': typeof LocaleExperiencesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/operator': typeof OperatorRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/$locale/operator': typeof LocaleOperatorRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/experiences/$slug': typeof LocaleExperiencesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/operator'
    | '/privacy'
    | '/search'
    | '/$locale/operator'
    | '/$locale/privacy'
    | '/$locale/search'
    | '/experiences/$slug'
    | '/$locale/'
    | '/$locale/experiences/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/operator'
    | '/privacy'
    | '/search'
    | '/$locale/operator'
    | '/$locale/privacy'
    | '/$locale/search'
    | '/experiences/$slug'
    | '/$locale'
    | '/$locale/experiences/$slug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/operator'
    | '/privacy'
    | '/search'
    | '/$locale/operator'
    | '/$locale/privacy'
    | '/$locale/search'
    | '/experiences/$slug'
    | '/$locale/'
    | '/$locale/experiences/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  OperatorRoute: typeof OperatorRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/operator': {
      id: '/$locale/operator'
      path: '/operator'
      fullPath: '/$locale/operator'
      preLoaderRoute: typeof LocaleOperatorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/experiences/$slug': {
      id: '/$locale/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/$locale/experiences/$slug'
      preLoaderRoute: typeof LocaleExperiencesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleOperatorRoute: typeof LocaleOperatorRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleExperiencesSlugRoute: typeof LocaleExperiencesSlugRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleOperatorRoute: LocaleOperatorRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleExperiencesSlugRoute: LocaleExperiencesSlugRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  OperatorRoute: OperatorRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
